### PR TITLE
Fix bug in editor.css with a crutch

### LINKED ISSUE #2: Bug in editor in chromium
Hello!

The page looks strange in the Cromium (Version 52.0.2743.116 Built on Ubuntu)

selection_011

### PR DESCRIPTION
**Pull request by maxkoryukov**
Set the same font size for both text-blocks.

fix #2

### CODE REVIEW

**Comment by vanwagonet** [comment]
thanks!

**Comment by maxkoryukov** [comment]
Will the github-pages be updated automatically?

**Comment by vanwagonet** [comment]
no, but I'll update it now.

**Comment by maxkoryukov** [comment]
Great! Now it looks well) Thank you!

**Pull request merged**
